### ISSUE TITLE
scvi-tools autotuning with Ray Tune

### ISSUE THREAD

**Issue by martinkim0** [scverse/scvi-tools#1721]
This issue will serve as a parent thread for all issues related to supporting autotuning with Ray Tune.

### Basic
- [x] Implement a basic working `ModelTuner` API #1720 

### Docs and tutorials
- [x] Add autotune to docs
- [x] Add tutorial: basic usage with scVI
- [x] Add tutorial: advanced usage with new model class

### Metrics
- [ ] Refactor PL logged metric keys for better visibility and consistency #1798 
- [ ] Allow usage of scib-metrics
- [x] Allow for custom metrics with a callback

### Miscellaneous
- [x] Refactor training mixins for consistency #1796 
- [x] Define tunables at the base class level for simplicity #1799
- [x] More comprehensive testing for the module
- [x] Enable logging with wandb for monitoring
- [ ] Discover better defaults for models #1616
