### ISSUE TITLE
[Meta] Upload pre-trained models to huggingface

### ISSUE THREAD

**Issue by adamgayoso** [scverse/scvi-tools#1814]
Let's make a list here of the pre-trained models to upload.

🔥 Remember to update the [scvi-hub-reference](https://github.com/YosefLab/scvi-hub-references) repo for each of these.

**Comment by watiss** [comment]
- [ ] pre-trained models for the scrna pretraining step of destvi and stereoscope
- [ ] Fetal immune (emma dann)
- [ ] HLCA
- [ ] Non small cell lung cancer (gregor strum)
- [ ] Tabula sapiens (pan tissue and tissue specific)
- [ ] Tabula sapiens (tissue specific)
- [ ] Seurat v4 cite-seq pbmc (from our tutorial)
