### ISSUE TITLE
Multi-GPU support tracker

### ISSUE THREAD

**Issue by martinkim0** [scverse/scvi-tools#2175]
- [x] Batch distributed sampler for efficient distributed sparse batching #2102 
- [ ] Jax multi-device with `pmap`
- [x] Multi-device flag in pytest
- [ ] Integrate with Lightning CI for Azure GPU resources #1314
