### ISSUE TITLE
Release scvi-tools 1.1.0-rc.1

### ISSUE THREAD

**Issue by martinkim0** [scverse/scvi-tools#2327]
-   [x] Bump version in `pyproject.toml`. #2358 
-   [x] If patch release, backport version bump PR into the appropriate branch. Else, create a new branch off `main` with the appropriate rules. https://github.com/scverse/scvi-tools/tree/1.1.x
-   [x] Create a new GitHub draft release targeting the release branch with the same body as the previous release (don't release yet). https://github.com/scverse/scvi-tools/releases/tag/untagged-ae349b909e1ef23aba36
-   [x] Trigger a Docker image build in [`scvi-tools-docker`](https://github.com/YosefLab/scvi-tools-docker) targeting the release branch. https://github.com/YosefLab/scvi-tools-docker/actions/runs/7119951398
-   [x] After image builds and pushes to the registry, run the [tutorials](https://github.com/scverse/scvi-tutorials) using the new image. https://github.com/scverse/scvi-tutorials/issues/209
-   [x] Publish a new release on the tutorials repo off `main` after all tutorials changes have been merged. https://github.com/scverse/scvi-tutorials/releases/tag/1.1.0rc1
-   [x] Create a new branch off `main` in the main repo and run `git submodule update --remote`, and then merge the PR, with an appropriate backport as needed. #2356 #2357 
-   [x] Double check everything and then publish the release on the main repo. https://github.com/scverse/scvi-tools/releases/tag/1.1.0rc1
-   [ ] Check that the [feedstock repo](https://github.com/conda-forge/scvi-tools-feedstock) updates correctly.
-   [x] Check that the version updates correctly on [PyPI](https://pypi.org/project/scvi-tools/). https://pypi.org/project/scvi-tools/1.1.0rc1/
-   [ ] (Optional) Post threads on Discourse and Twitter!
