### ISSUE TITLE
Release scvi-tools 1.1.0-rc.2

### ISSUE THREAD

**Issue by martinkim0** [scverse/scvi-tools#2360]
-   [x] Bump version in `pyproject.toml`. #2400 
-   [x] If patch release, backport version bump PR into the appropriate branch. Else, create a new branch off `main` with the appropriate rules. #2401 
-   [x] Create a new GitHub draft release targeting the release branch with the same body as the previous release (don't release yet). https://github.com/scverse/scvi-tools/releases/tag/untagged-6d79987a12fca006b79a
-   [ ] ~Trigger a Docker image build in [`scvi-tools-docker`](https://github.com/YosefLab/scvi-tools-docker) targeting the release branch.~
-   [ ] ~After image builds and pushes to the registry, run the [tutorials](https://github.com/scverse/scvi-tutorials) using the new image.~
-   [x] Publish a new release on the tutorials repo off `main` after all tutorials changes have been merged. https://github.com/scverse/scvi-tutorials/releases/tag/1.1.0rc2
-   [x] Create a new branch off `main` in the main repo and run `git submodule update --remote`, and then merge the PR, with an appropriate backport as needed. #2402 #2403 
-   [x] Double check everything and then publish the draft release on the main repo. https://github.com/scverse/scvi-tools/releases/tag/1.1.0rc2
-   [ ] ~Check that the [feedstock repo](https://github.com/conda-forge/scvi-tools-feedstock) updates correctly.~
-   [x] Check that the version updates correctly on [PyPI](https://pypi.org/project/scvi-tools/). https://pypi.org/project/scvi-tools/1.1.0rc2/
-   [ ] ~(Optional) Post threads on Discourse and Twitter!~
