### ISSUE TITLE
Release scvi-tools 1.1.0

### ISSUE THREAD

**Issue by martinkim0** [scverse/scvi-tools#2411]
-   [x] Bump version in `pyproject.toml` #2462 
-   [ ] ~If patch release, backport version bump PR into the appropriate branch. Else, create a new branch off `main` with the appropriate rules~
-   [x] Trigger a Docker image build in [`scvi-tools-docker`](https://github.com/YosefLab/scvi-tools-docker) targeting the release branch https://github.com/YosefLab/scvi-tools-docker/actions/runs/7863237209
-   [x] After image builds and pushes to the registry, run the [tutorials](https://github.com/scverse/scvi-tutorials) using the new image https://github.com/scverse/scvi-tutorials/issues/210
-   [x] Publish a new release on the tutorials repo off `main` after all tutorials changes have been merged https://github.com/scverse/scvi-tutorials/releases/tag/1.1.0
-   [x] Create a new branch off `main` in the main repo and run `git submodule update --remote`, and then merge the PR, with an appropriate backport as needed #2508 #2509
-   [x] Create a new GitHub release targeting the release branch with the same body as the previous release https://github.com/scverse/scvi-tools/releases/tag/1.1.0
-   [x] Check that the version updates correctly on [PyPI](https://pypi.org/project/scvi-tools/) https://pypi.org/project/scvi-tools/1.1.0.post1/
-   [x] Check that the [feedstock repo](https://github.com/conda-forge/scvi-tools-feedstock) updates correctly https://github.com/conda-forge/scvi-tools-feedstock/pull/40
-   [x] (Optional) Post threads on Discourse and Twitter
